### PR TITLE
Fixed bugs and added makefile

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
Fixed bugs on a new version:

- `weather2.c`:68:5: error: Memory leak: api_key [memleak] ` return 1;`
- `weather2.c`:258:55: error: Null pointer dereference [nullPointer]  `printf("Memory allocation unsuccessfull for %s!", x);`

Added Makefile for easier compilation.

**Note:** Your code on `weather.c` compiles and runs without a problem. I just fixed these 2 mistakes. You can keep both versions.

### CODE REVIEW

**Comment by CoutHi** [comment]
I will take a look at it, could you take a look at the new repo for mounter? There were some issues with your previous code and I tangled all the branches together trying to revert it, at the end it was all messed up and I had to nuke the repo. Sorry, new at this :)

Edit: I would also like to suggest, you don't create a secondary C file for your commits, I do keep my old versions around anyways, so please overwrite the original file so the changes are shown to me much more clearly.

**Comment by mgiannopoulos24** [comment]
Alright. I made an issue to contact you but no problem.

**Comment by CoutHi** [comment]
I haven't been able to find the change you made on line 68, it looks identical to the original code. I'd also be modifying the name of the source file to weather.c and removing the old source file from the Makefile after merging, you might want to do so yourself if you want to. Line 258 looks great, no idea how I came up with that catastrophe :)

**Comment by mgiannopoulos24** [comment]
`cppcheck` told me the line with the problem was 68. I assume because you never freed the allocated memory of the api key. On line 17-18 I freed the api key and it works just fine.

**Comment by mgiannopoulos24** [comment]
I looked it up a bit better.

The memory leak from the not freed `api_key` occurs because if the program exits at this point due to the failure to open the file, the `api_key` (as well as other dynamically allocated memory) will not be freed. This is because the program exits before reaching the part of the code where `api_key` and other allocated memory are freed.

**Comment by CoutHi** [comment]
Ah I see now, I wasn't able to locate the line you have added before. Problem with freeing it there is that we need that variable later on to form the url to get the weather information. if we free it there we won't be able to get the proper url to call.

**Comment by mgiannopoulos24** [comment]
Okay then. Modify it as you wish 😄

**Comment by CoutHi** [comment]
Alright, otherwise it looks good and I'll see what I can do about that variable, thank you.

**Pull request merged**
